
cache: apt

language: go
go:
  - 1.4.1

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get -t -v ./...

script:
  - go test -v -cover 

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
